package io.github.gmerick.inventory;

import java.sql.*;
import java.util.*;

/** JDBC puro: cada operação abre e fecha sua própria conexão. */
public final class InventoryRepository {
  private final String url;

  public InventoryRepository(String url) throws SQLException {
    this.url = url;
    try (Connection c = connect();
        Statement s = c.createStatement()) {
      s.execute(
          "CREATE TABLE IF NOT EXISTS products (sku VARCHAR(30) PRIMARY KEY, name VARCHAR(120) NOT"
              + " NULL, quantity INT NOT NULL DEFAULT 0 CHECK(quantity >= 0), minimum INT NOT NULL"
              + " CHECK(minimum >= 0))");
      s.execute(
          "CREATE TABLE IF NOT EXISTS movements (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY"
              + " KEY, sku VARCHAR(30) NOT NULL REFERENCES products(sku), delta INT NOT NULL"
              + " CHECK(delta <> 0), reason VARCHAR(200) NOT NULL, created_at TIMESTAMP NOT NULL"
              + " DEFAULT CURRENT_TIMESTAMP)");
    }
  }

  private Connection connect() throws SQLException {
    return DriverManager.getConnection(url, "sa", "");
  }

  public void add(String sku, String name, int minimum) throws SQLException {
    try (Connection c = connect();
        PreparedStatement p =
            c.prepareStatement("INSERT INTO products(sku,name,minimum) VALUES(?,?,?)")) {
      p.setString(1, sku);
      p.setString(2, name);
      p.setInt(3, minimum);
      p.executeUpdate();
    }
  }

  public List<Product> list() throws SQLException {
    List<Product> products = new ArrayList<>();
    try (Connection c = connect();
        PreparedStatement p = c.prepareStatement("SELECT * FROM products ORDER BY sku");
        ResultSet rs = p.executeQuery()) {
      while (rs.next())
        products.add(
            new Product(
                rs.getString("sku"),
                rs.getString("name"),
                rs.getInt("quantity"),
                rs.getInt("minimum")));
    }
    return List.copyOf(products);
  }

  /**
   * Saldo e auditoria são gravados na mesma transação. O UPDATE protege contra saídas concorrentes.
   */
  public void move(String sku, int delta, String reason) throws SQLException {
    try (Connection c = connect()) {
      c.setAutoCommit(false);
      try {
        try (PreparedStatement p =
            c.prepareStatement(
                "UPDATE products SET quantity=quantity+? WHERE sku=? AND CAST(quantity AS BIGINT)+?"
                    + " BETWEEN 0 AND 2147483647")) {
          p.setInt(1, delta);
          p.setString(2, sku);
          p.setInt(3, delta);
          if (p.executeUpdate() != 1)
            throw new IllegalArgumentException(
                "Produto inexistente, saldo insuficiente ou limite de estoque excedido.");
        }
        try (PreparedStatement p =
            c.prepareStatement("INSERT INTO movements(sku,delta,reason) VALUES(?,?,?)")) {
          p.setString(1, sku);
          p.setInt(2, delta);
          p.setString(3, reason);
          p.executeUpdate();
        }
        c.commit();
      } catch (SQLException | RuntimeException e) {
        c.rollback();
        throw e;
      }
    }
  }

  public List<Movement> history(String sku) throws SQLException {
    List<Movement> movements = new ArrayList<>();
    try (Connection c = connect();
        PreparedStatement p =
            c.prepareStatement("SELECT * FROM movements WHERE sku=? ORDER BY id")) {
      p.setString(1, sku);
      try (ResultSet rs = p.executeQuery()) {
        while (rs.next())
          movements.add(
              new Movement(
                  rs.getLong("id"),
                  rs.getString("sku"),
                  rs.getInt("delta"),
                  rs.getString("reason"),
                  rs.getString("created_at")));
      }
    }
    return List.copyOf(movements);
  }
}
