spring.application.name=java-it-inventory
server.address=${SERVER_ADDRESS:127.0.0.1}
server.port=${PORT:8080}
inventory.db-url=${INVENTORY_DB_URL:jdbc:h2:file:./data/inventory}
spring.jackson.deserialization.fail-on-unknown-properties=true
server.error.include-message=never
